server:
  port: ${BOOK_SERVICE_PORT:9001}
spring:
  servlet:
    multipart:
      max-file-size: 5MB  
  data:
    mongodb:
      database: books_dbnew
      port: ${MONGO_PORT:27017}
      host: ${MONGO_HOST:localhost}    


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/
  instance:
    preferIpAddress: true    
  
